// Inhabited islands of the Maldives, grouped by administrative atoll.
// Used to power the searchable location picker. This covers the ~190
// inhabited islands (not every uninhabited/resort island) since that's
// where service visits happen; the picker also accepts free-text entry
// for anything not listed (e.g. a specific resort).
const MALDIVES_ISLANDS = [
  { atoll: "HA", atollName: "Haa Alif", island: "Dhidhdhoo", capital: true },
  { atoll: "HA", atollName: "Haa Alif", island: "Baarah" },
  { atoll: "HA", atollName: "Haa Alif", island: "Filladhoo" },
  { atoll: "HA", atollName: "Haa Alif", island: "Hoarafushi" },
  { atoll: "HA", atollName: "Haa Alif", island: "Ihavandhoo" },
  { atoll: "HA", atollName: "Haa Alif", island: "Kelaa" },
  { atoll: "HA", atollName: "Haa Alif", island: "Maarandhoo" },
  { atoll: "HA", atollName: "Haa Alif", island: "Mulhadhoo" },
  { atoll: "HA", atollName: "Haa Alif", island: "Muraidhoo" },
  { atoll: "HA", atollName: "Haa Alif", island: "Thakandhoo" },
  { atoll: "HA", atollName: "Haa Alif", island: "Thuraakunu" },
  { atoll: "HA", atollName: "Haa Alif", island: "Uligamu" },
  { atoll: "HA", atollName: "Haa Alif", island: "Utheemu" },
  { atoll: "HA", atollName: "Haa Alif", island: "Vashafaru" },

  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Kulhudhuffushi", capital: true },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Finey" },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Hanimaadhoo" },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Hirimaradhoo" },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Kumundhoo" },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Kurinbi" },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Makunudhoo" },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Naivaadhoo" },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Nellaidhoo" },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Neykurendhoo" },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Nolhivaramu" },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Nolhivaranfaru" },
  { atoll: "HDh", atollName: "Haa Dhaalu", island: "Vaikaradhoo" },

  { atoll: "Sh", atollName: "Shaviyani", island: "Funadhoo", capital: true },
  { atoll: "Sh", atollName: "Shaviyani", island: "Feevah" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Feydhoo" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Foakaidhoo" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Goidhoo" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Kanditheemu" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Lhaimagu" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Maaungoodhoo" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Maroshi" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Milandhoo" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Narudhoo" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Noomaraa" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Bileffahi" },
  { atoll: "Sh", atollName: "Shaviyani", island: "Komandoo" },

  { atoll: "N", atollName: "Noonu", island: "Manadhoo", capital: true },
  { atoll: "N", atollName: "Noonu", island: "Miladhoo" },
  { atoll: "N", atollName: "Noonu", island: "Maafaru" },
  { atoll: "N", atollName: "Noonu", island: "Magoodhoo" },
  { atoll: "N", atollName: "Noonu", island: "Maalhendhoo" },
  { atoll: "N", atollName: "Noonu", island: "Kudafari" },
  { atoll: "N", atollName: "Noonu", island: "Holhudhoo" },
  { atoll: "N", atollName: "Noonu", island: "Fodhdhoo" },
  { atoll: "N", atollName: "Noonu", island: "Lhohi" },
  { atoll: "N", atollName: "Noonu", island: "Velidhoo" },
  { atoll: "N", atollName: "Noonu", island: "Kendhikulhudhoo" },
  { atoll: "N", atollName: "Noonu", island: "Landhoo" },
  { atoll: "N", atollName: "Noonu", island: "Henbadhoo" },
  { atoll: "N", atollName: "Noonu", island: "Maduvvari" },

  { atoll: "R", atollName: "Raa", island: "Ungoofaaru", capital: true },
  { atoll: "R", atollName: "Raa", island: "Alifushi" },
  { atoll: "R", atollName: "Raa", island: "Angolhitheemu" },
  { atoll: "R", atollName: "Raa", island: "Fainu" },
  { atoll: "R", atollName: "Raa", island: "Hulhudhuffaaru" },
  { atoll: "R", atollName: "Raa", island: "Inguraidhoo" },
  { atoll: "R", atollName: "Raa", island: "Innamaadhoo" },
  { atoll: "R", atollName: "Raa", island: "Dhuvaafaru" },
  { atoll: "R", atollName: "Raa", island: "Kinolhas" },
  { atoll: "R", atollName: "Raa", island: "Maakurathu" },
  { atoll: "R", atollName: "Raa", island: "Maduvvaree" },
  { atoll: "R", atollName: "Raa", island: "Meedhoo" },
  { atoll: "R", atollName: "Raa", island: "Rasgetheemu" },
  { atoll: "R", atollName: "Raa", island: "Rasmaadhoo" },
  { atoll: "R", atollName: "Raa", island: "Vaadhoo" },
  { atoll: "R", atollName: "Raa", island: "Kandholhudhoo" },

  { atoll: "B", atollName: "Baa", island: "Eydhafushi", capital: true },
  { atoll: "B", atollName: "Baa", island: "Dharavandhoo" },
  { atoll: "B", atollName: "Baa", island: "Dhonfanu" },
  { atoll: "B", atollName: "Baa", island: "Fehendhoo" },
  { atoll: "B", atollName: "Baa", island: "Fulhadhoo" },
  { atoll: "B", atollName: "Baa", island: "Goidhoo" },
  { atoll: "B", atollName: "Baa", island: "Hithaadhoo" },
  { atoll: "B", atollName: "Baa", island: "Kamadhoo" },
  { atoll: "B", atollName: "Baa", island: "Kendhoo" },
  { atoll: "B", atollName: "Baa", island: "Kihaadhoo" },
  { atoll: "B", atollName: "Baa", island: "Kudarikilu" },
  { atoll: "B", atollName: "Baa", island: "Maalhos" },
  { atoll: "B", atollName: "Baa", island: "Thulhaadhoo" },

  { atoll: "Lh", atollName: "Lhaviyani", island: "Naifaru", capital: true },
  { atoll: "Lh", atollName: "Lhaviyani", island: "Hinnavaru" },
  { atoll: "Lh", atollName: "Lhaviyani", island: "Kurendhoo" },
  { atoll: "Lh", atollName: "Lhaviyani", island: "Olhuvelifushi" },

  { atoll: "K", atollName: "Kaafu", island: "Male", capital: true },
  { atoll: "K", atollName: "Kaafu", island: "Hulhumale" },
  { atoll: "K", atollName: "Kaafu", island: "Villimale" },
  { atoll: "K", atollName: "Kaafu", island: "Thulusdhoo" },
  { atoll: "K", atollName: "Kaafu", island: "Dhiffushi" },
  { atoll: "K", atollName: "Kaafu", island: "Gaafaru" },
  { atoll: "K", atollName: "Kaafu", island: "Guraidhoo" },
  { atoll: "K", atollName: "Kaafu", island: "Gulhi" },
  { atoll: "K", atollName: "Kaafu", island: "Himmafushi" },
  { atoll: "K", atollName: "Kaafu", island: "Huraa" },
  { atoll: "K", atollName: "Kaafu", island: "Kaashidhoo" },
  { atoll: "K", atollName: "Kaafu", island: "Maafushi" },

  { atoll: "AA", atollName: "Alif Alif", island: "Rasdhoo", capital: true },
  { atoll: "AA", atollName: "Alif Alif", island: "Bodufolhudhoo" },
  { atoll: "AA", atollName: "Alif Alif", island: "Feridhoo" },
  { atoll: "AA", atollName: "Alif Alif", island: "Himandhoo" },
  { atoll: "AA", atollName: "Alif Alif", island: "Maalhos" },
  { atoll: "AA", atollName: "Alif Alif", island: "Mathiveri" },
  { atoll: "AA", atollName: "Alif Alif", island: "Thoddoo" },
  { atoll: "AA", atollName: "Alif Alif", island: "Ukulhas" },

  { atoll: "ADh", atollName: "Alif Dhaal", island: "Mahibadhoo", capital: true },
  { atoll: "ADh", atollName: "Alif Dhaal", island: "Dangethi" },
  { atoll: "ADh", atollName: "Alif Dhaal", island: "Dhidhdhoo" },
  { atoll: "ADh", atollName: "Alif Dhaal", island: "Dhigurah" },
  { atoll: "ADh", atollName: "Alif Dhaal", island: "Fenfushi" },
  { atoll: "ADh", atollName: "Alif Dhaal", island: "Hangnaameedhoo" },
  { atoll: "ADh", atollName: "Alif Dhaal", island: "Kunburudhoo" },
  { atoll: "ADh", atollName: "Alif Dhaal", island: "Maamigili" },
  { atoll: "ADh", atollName: "Alif Dhaal", island: "Mandhoo" },
  { atoll: "ADh", atollName: "Alif Dhaal", island: "Omadhoo" },

  { atoll: "V", atollName: "Vaavu", island: "Felidhoo", capital: true },
  { atoll: "V", atollName: "Vaavu", island: "Fulidhoo" },
  { atoll: "V", atollName: "Vaavu", island: "Keyodhoo" },
  { atoll: "V", atollName: "Vaavu", island: "Rakeedhoo" },
  { atoll: "V", atollName: "Vaavu", island: "Thinadhoo" },

  { atoll: "M", atollName: "Meemu", island: "Muli", capital: true },
  { atoll: "M", atollName: "Meemu", island: "Dhiggaru" },
  { atoll: "M", atollName: "Meemu", island: "Kolhufushi" },
  { atoll: "M", atollName: "Meemu", island: "Maduvvaree" },
  { atoll: "M", atollName: "Meemu", island: "Mulah" },
  { atoll: "M", atollName: "Meemu", island: "Naalaafushi" },
  { atoll: "M", atollName: "Meemu", island: "Raimmandhoo" },
  { atoll: "M", atollName: "Meemu", island: "Veyvah" },

  { atoll: "F", atollName: "Faafu", island: "Nilandhoo", capital: true },
  { atoll: "F", atollName: "Faafu", island: "Bileddhoo" },
  { atoll: "F", atollName: "Faafu", island: "Dharanboodhoo" },
  { atoll: "F", atollName: "Faafu", island: "Feeali" },
  { atoll: "F", atollName: "Faafu", island: "Magoodhoo" },

  { atoll: "Dh", atollName: "Dhaalu", island: "Kudahuvadhoo", capital: true },
  { atoll: "Dh", atollName: "Dhaalu", island: "Bandidhoo" },
  { atoll: "Dh", atollName: "Dhaalu", island: "Hulhudheli" },
  { atoll: "Dh", atollName: "Dhaalu", island: "Maaenboodhoo" },
  { atoll: "Dh", atollName: "Dhaalu", island: "Meedhoo" },
  { atoll: "Dh", atollName: "Dhaalu", island: "Rinbudhoo" },
  { atoll: "Dh", atollName: "Dhaalu", island: "Vaanee" },

  { atoll: "Th", atollName: "Thaa", island: "Veymandoo", capital: true },
  { atoll: "Th", atollName: "Thaa", island: "Buruni" },
  { atoll: "Th", atollName: "Thaa", island: "Dhiyamigili" },
  { atoll: "Th", atollName: "Thaa", island: "Guraidhoo" },
  { atoll: "Th", atollName: "Thaa", island: "Hirilandhoo" },
  { atoll: "Th", atollName: "Thaa", island: "Kadoodhoo" },
  { atoll: "Th", atollName: "Thaa", island: "Kibidhoo" },
  { atoll: "Th", atollName: "Thaa", island: "Madifushi" },
  { atoll: "Th", atollName: "Thaa", island: "Omadhoo" },
  { atoll: "Th", atollName: "Thaa", island: "Thimarafushi" },
  { atoll: "Th", atollName: "Thaa", island: "Vandhoo" },
  { atoll: "Th", atollName: "Thaa", island: "Vilufushi" },
  { atoll: "Th", atollName: "Thaa", island: "Gaadhiffushi" },

  { atoll: "L", atollName: "Laamu", island: "Fonadhoo", capital: true },
  { atoll: "L", atollName: "Laamu", island: "Dhanbidhoo" },
  { atoll: "L", atollName: "Laamu", island: "Gan" },
  { atoll: "L", atollName: "Laamu", island: "Hithadhoo" },
  { atoll: "L", atollName: "Laamu", island: "Isdhoo" },
  { atoll: "L", atollName: "Laamu", island: "Kalaidhoo" },
  { atoll: "L", atollName: "Laamu", island: "Kunahandhoo" },
  { atoll: "L", atollName: "Laamu", island: "Maabaidhoo" },
  { atoll: "L", atollName: "Laamu", island: "Maamendhoo" },
  { atoll: "L", atollName: "Laamu", island: "Maandhoo" },
  { atoll: "L", atollName: "Laamu", island: "Maavah" },
  { atoll: "L", atollName: "Laamu", island: "Mundoo" },
  { atoll: "L", atollName: "Laamu", island: "Gaadhoo" },

  { atoll: "GA", atollName: "Gaafu Alif", island: "Viligili", capital: true },
  { atoll: "GA", atollName: "Gaafu Alif", island: "Dhaandhoo" },
  { atoll: "GA", atollName: "Gaafu Alif", island: "Dhevvadhoo" },
  { atoll: "GA", atollName: "Gaafu Alif", island: "Gemanafushi" },
  { atoll: "GA", atollName: "Gaafu Alif", island: "Kanduhulhudhoo" },
  { atoll: "GA", atollName: "Gaafu Alif", island: "Kolamaafushi" },
  { atoll: "GA", atollName: "Gaafu Alif", island: "Kondey" },
  { atoll: "GA", atollName: "Gaafu Alif", island: "Maamendhoo" },
  { atoll: "GA", atollName: "Gaafu Alif", island: "Nilandhoo" },
  { atoll: "GA", atollName: "Gaafu Alif", island: "Dhiyadhoo" },

  { atoll: "GDh", atollName: "Gaafu Dhaalu", island: "Thinadhoo", capital: true },
  { atoll: "GDh", atollName: "Gaafu Dhaalu", island: "Fares-Maathodaa" },
  { atoll: "GDh", atollName: "Gaafu Dhaalu", island: "Fiyoaree" },
  { atoll: "GDh", atollName: "Gaafu Dhaalu", island: "Gadhdhoo" },
  { atoll: "GDh", atollName: "Gaafu Dhaalu", island: "Hoandeddhoo" },
  { atoll: "GDh", atollName: "Gaafu Dhaalu", island: "Madaveli" },
  { atoll: "GDh", atollName: "Gaafu Dhaalu", island: "Nadellaa" },
  { atoll: "GDh", atollName: "Gaafu Dhaalu", island: "Rathafandhoo" },
  { atoll: "GDh", atollName: "Gaafu Dhaalu", island: "Vaadhoo" },

  { atoll: "Gn", atollName: "Gnaviyani", island: "Fuvahmulah", capital: true },

  { atoll: "S", atollName: "Seenu", island: "Hithadhoo", capital: true },
  { atoll: "S", atollName: "Seenu", island: "Maradhoo" },
  { atoll: "S", atollName: "Seenu", island: "Maradhoo-Feydhoo" },
  { atoll: "S", atollName: "Seenu", island: "Feydhoo" },
  { atoll: "S", atollName: "Seenu", island: "Hulhudhoo" },
  { atoll: "S", atollName: "Seenu", island: "Meedhoo" },
  { atoll: "S", atollName: "Seenu", island: "Gan" },
];

export default MALDIVES_ISLANDS;
